### ISSUE TITLE
Handle error in `GraphicsVizualizerBuilder.build` and show in the editor

### ISSUE THREAD

**Issue by dj2** [google/tour-of-wgsl#72]
In Chrome 111, the tour canvas does not show anything, there is no error in the editor. The following appears in the console:

```
TypeError: shaderModule.getCompilationInfo is not a function
    at GraphicsVizualizerBuilder.build (graphics_visualizer.js:106:48)
    at WGSLTour.buildVisualization (app.46a75e8e455d318a91b0ed119744fd40281d20464753492d0279a5ca08041543.js:186281:33)
    at WGSLTour.setVisualizationBuilder (app.46a75e8e455d318a91b0ed119744fd40281d20464753492d0279a5ca08041543.js:186269:12)
```

We should catch the error and display a message in the editor that that Chrome is too old.

**Comment by ben-clayton** [comment]
I believe this API was renamed. We could try to handle the old version for a while.
